apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: blue  # Switch to green for promoting green version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
